In [2]:
import tensorflow as tf
import numpy as np

a = tf.random.uniform(shape = [16,16],minval = 0,maxval = 101,dtype = tf.int32)
b = tf.random.uniform(shape = [16,16],minval = 0,maxval = 101,dtype = tf.int32)

In [3]:
print(tf.add(a,b))

tf.Tensor(
[[ 96 119 119  90  81 158 139  96  65 120  34  22 107 108 126 103]
 [ 32 113 119 111 101 101  83 146  68 112 131  32  76 138 139 113]
 [ 84 147  88  83 105 110 105 120  92   8 115  68 118  86  94 101]
 [ 84 141  23 103  89 122 111 151 112  61  85 143 186 127 115 103]
 [ 92 100  10  80  95 113 165 147 107  65 131 104 104  53 120  36]
 [ 65  39  43 146 129  88  78 152  74  88 126  24  36  47  81  66]
 [ 23  80  82  59 114  83  90 152  28  79 146  27  69 131 148 174]
 [ 76 109 171  69 124  96 148 118  29 115 144 169  94 124  68  20]
 [111 122  69  76  26  89  97 127  88  51 121 144  40  91 124  10]
 [105  99  80  38  84 147 113  52 140 149 110 100  95  36 140 153]
 [163  82  24 158  40  82  51 179 128  76  86 115  92 115  63  58]
 [ 89  60 146  33 173  77  98 149  87 129 152 148 144 117 132 116]
 [ 36 151  77  61 190 130  61  84 174  91  37  44  91  67 130 131]
 [134  31 151  29  99 100  56   6 182 173  70  77 125  24  55  95]
 [101 123 104 122 101  33 103 102  52 126  88 123  

In [4]:
print(tf.subtract(a,b))

tf.Tensor(
[[ 48  29 -61  50 -81  36 -13  94  51 -26   8   4 -65 -36  16  93]
 [-20  35   1 -63 -85  45 -33  36 -10 -74 -53  18  26  30 -37  77]
 [-40 -43 -72   1 -43 -38  67 -16  50  -2 -77  54  38 -18  28  87]
 [-60   3 -19  39   7  16  -1 -41  64  19  25   7 -12   3 -69 -33]
 [ 30 -30  -2 -40 -89 -63 -31  -3 -51  51  -1  26 -46  31  54 -12]
 [-33  11   1   8  19 -16 -60   0  70 -80  18  16  20 -19 -59   2]
 [-19 -72 -32 -39 -78 -55  88  46  -8  25   8 -13  51   9 -42 -16]
 [-74  77   3 -57 -54 -72 -14 -66  13  -5 -46  -7  86   2 -26  -2]
 [ 39  34 -17  10 -24  75 -91  29 -74  37  55 -40  26  39  -6 -10]
 [ 63  49  80  12 -62   3 -11  18 -42  35  56  92  27  -2 -22  11]
 [ 13  26  -8  42  34   8  47 -13  60  68 -76  51 -54  47 -25  52]
 [ 61 -32   4  17 -15 -23  96 -51  13  57  30  10   6 -49 -20   0]
 [ 12  41  31 -25  10  -6 -61  34  12  35 -31 -36   7 -55 -60  11]
 [ -8 -31  -3 -11  45  92  52  -4  14 -21  32 -13  41  14  -7 -65]
 [-93 -55  74 -42   1  -3  37  66  32 -52  12 -35  

In [5]:
print(tf.multiply(a,b))

tf.Tensor(
[[1728 3330 2610 1400    0 5917 4788   95  406 3431  273  117 1806 2592
  3905  490]
 [ 156 2886 3540 2088  744 2044 1450 5005 1131 1767 3588  175 1275 4536
  4488 1710]
 [1364 4940  640 1722 2294 2664 1634 3536 1491   15 1824  427 3120 1768
  2013  658]
 [ 864 4968   42 2272 1968 3657 3080 5280 2112  840 1650 5100 8613 4030
  2116 2380]
 [1891 2275   24 1200  276 2200 6566 5400 2212  406 4290 2535 2175  462
  2871  288]
 [ 784  350  462 5313 4070 1872  621 5776  144  336 3888   80  224  462
   770 1088]
 [  42  304 1425  490 1728  966   89 5247  180 1404 5313  140  540 4270
  5035 7505]
 [  75 1488 7308  378 3115 1008 5427 2392  168 3300 4655 7128  360 3843
   987   99]
 [2700 3432 1118 1419   25  574  282 3822  567  308 2904 4784  231 1690
  3835    0]
 [1764 1850    0  325  803 5400 3162  595 4459 5244 2241  384 2074  323
  4779 5822]
 [6600 1512  128 5800  111 1665   98 7968 3196  288  405 2656 1387 2754
   836  165]
 [1050  644 5325  200 7426 1350   97 4900 1850 3348 55

In [6]:
print(tf.divide(a,b))

tf.Tensor(
[[3.00000000e+00 1.64444444e+00 3.22222222e-01 3.50000000e+00
  0.00000000e+00 1.59016393e+00 8.28947368e-01 9.50000000e+01
  8.28571429e+00 6.43835616e-01 1.61538462e+00 1.44444444e+00
  2.44186047e-01 5.00000000e-01 1.29090909e+00 1.96000000e+01]
 [2.30769231e-01 1.89743590e+00 1.01694915e+00 2.75862069e-01
  8.60215054e-02 2.60714286e+00 4.31034483e-01 1.65454545e+00
  7.43589744e-01 2.04301075e-01 4.23913043e-01 3.57142857e+00
  2.04000000e+00 1.55555556e+00 5.79545455e-01 5.27777778e+00]
 [3.54838710e-01 5.47368421e-01 1.00000000e-01 1.02439024e+00
  4.18918919e-01 4.86486486e-01 4.52631579e+00 7.64705882e-01
  3.38095238e+00 6.00000000e-01 1.97916667e-01 8.71428571e+00
  1.95000000e+00 6.53846154e-01 1.84848485e+00 1.34285714e+01]
 [1.66666667e-01 1.04347826e+00 9.52380952e-02 2.21875000e+00
  1.17073171e+00 1.30188679e+00 9.82142857e-01 5.72916667e-01
  3.66666667e+00 1.90476190e+00 1.83333333e+00 1.10294118e+00
  8.78787879e-01 1.04838710e+00 2.50000000e-01 5.1470588

In [7]:
tf.matmul(a,b)

<tf.Tensor: shape=(16, 16), dtype=int32, numpy=
array([[45372, 39192, 38865, 47968, 52400, 43246, 47859, 47203, 27488,
        43632, 48067, 39237, 30084, 38835, 58630, 30294],
       [41867, 33531, 35382, 43292, 44214, 36325, 36258, 42701, 28736,
        37189, 46468, 34997, 24796, 31432, 46866, 26098],
       [34858, 38009, 32241, 40690, 47583, 36786, 37578, 42267, 30502,
        30180, 42030, 39567, 27167, 34846, 52836, 30679],
       [37173, 37832, 34721, 40230, 52988, 40717, 42730, 50564, 39618,
        36699, 45617, 39790, 34228, 37396, 58911, 35605],
       [32843, 31319, 31082, 31158, 43412, 32697, 27791, 34809, 23837,
        35165, 35682, 30343, 26576, 30776, 45277, 27436],
       [31124, 26965, 22828, 30496, 33240, 31292, 35024, 41584, 24451,
        18528, 35219, 31304, 27300, 24998, 35886, 16794],
       [36883, 30906, 28195, 35973, 39267, 36134, 27819, 36210, 27786,
        27516, 40054, 32362, 22571, 27059, 42044, 28558],
       [28265, 36867, 34036, 32351, 51399, 37156,

In [8]:
tf.transpose(a)

<tf.Tensor: shape=(16, 16), dtype=int32, numpy=
array([[ 72,   6,  22,  12,  61,  16,   2,   1,  75,  84,  88,  75,  24,
         63,   4,   9],
       [ 74,  74,  52,  72,  35,  25,   4,  93,  78,  74,  54,  14,  96,
          0,  34,  98],
       [ 29,  60,   8,   2,   4,  22,  25,  87,  26,  80,   8,  75,  54,
         74,  89,   5],
       [ 70,  24,  42,  71,  20,  77,  10,   6,  43,  25, 100,  25,  18,
          9,  40,  30],
       [  0,   8,  31,  48,   3,  74,  18,  35,   1,  11,  37,  79, 100,
         72,  51,  70],
       [ 97,  73,  36,  69,  25,  36,  14,  12,  82,  75,  45,  27,  62,
         96,  15,  79],
       [ 63,  25,  86,  55,  67,   9,  89,  67,   3,  51,  49,  97,   0,
         54,  70,  12],
       [ 95,  91,  52,  55,  72,  76,  99,  26,  78,  35,  83,  49,  59,
          1,  84,  95],
       [ 58,  29,  71,  88,  28,  72,  10,  21,   7,  49,  94,  50,  93,
         98,  42,  27],
       [ 47,  19,   3,  40,  58,   4,  52,  55,  44,  92,  72,  93,  63,
      

In [13]:
tf.reduce_mean(b)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [14]:
c = tf.eye(num_rows = 16,dtype = tf.int32)
a+c

<tf.Tensor: shape=(16, 16), dtype=int32, numpy=
array([[ 73,  74,  29,  70,   0,  97,  63,  95,  58,  47,  21,  13,  21,
         36,  71,  98],
       [  6,  75,  60,  24,   8,  73,  25,  91,  29,  19,  39,  25,  51,
         84,  51,  95],
       [ 22,  52,   9,  42,  31,  36,  86,  52,  71,   3,  19,  61,  78,
         34,  61,  94],
       [ 12,  72,   2,  72,  48,  69,  55,  55,  88,  40,  55,  75,  87,
         65,  23,  35],
       [ 61,  35,   4,  20,   4,  25,  67,  72,  28,  58,  65,  65,  29,
         42,  87,  12],
       [ 16,  25,  22,  77,  74,  37,   9,  76,  72,   4,  72,  20,  28,
         14,  11,  34],
       [  2,   4,  25,  10,  18,  14,  90,  99,  10,  52,  77,   7,  60,
         70,  53,  79],
       [  1,  93,  87,   6,  35,  12,  67,  27,  21,  55,  49,  81,  90,
         63,  21,   9],
       [ 75,  78,  26,  43,   1,  82,   3,  78,   8,  44,  88,  52,  33,
         65,  59,   0],
       [ 84,  74,  80,  25,  11,  75,  51,  35,  49,  93,  83,  96,  61,
      

In [18]:
print(a[1:3,1:3])

tf.Tensor(
[[74 60]
 [52  8]], shape=(2, 2), dtype=int32)


In [39]:
model = tf.keras.Sequential([tf.keras.layers.Dense(1)])
model.compile(optimizer='adam', loss='mse')
model.fit(a, b, epochs=1000, verbose=1)

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 654ms/step - loss: 9362.2656
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - loss: 9229.1904
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 9097.3828
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 8966.8633
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 8837.6523
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 8709.7715
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 8583.2402
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 8458.0762
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 8334.2949
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 8211.9141
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 8090.9512
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 7971.4194
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 7853.3306
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 7736.6992
Epoch 15/1000
1/1 ━━━━━━━━━

In [41]:
print("Prediction for x=1:", model.predict(tf.constant(np.full((1, 16), 1.0), dtype=tf.float32))[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
Prediction for x=1: 0.980494


In [52]:
import torch
import torch.nn as nn
import torch.optim as optim

# Data: 16 samples, each with 16 features → predict 16 targets
A = torch.randint(low=0, high=101, size=(16, 16), dtype=torch.float32)
B = torch.randint(low=0, high=101, size=(16, 16), dtype=torch.float32)

# (Optional) normalize to help training
A = A / 100.0
B = B / 100.0

# Model: 16 → 64 → 64 → 16
model = nn.Sequential(
    nn.Linear(16, 64),
    nn.ReLU(),
    nn.Linear(64, 64),
    nn.ReLU(),
    nn.Linear(64, 16)
)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

# Train
model.train()
for epoch in range(500):
    optimizer.zero_grad()
    pred = model(A)          # (16,16) -> (16,16)
    loss = criterion(pred, B)
    loss.backward()
    optimizer.step()

# Test on a 16-d vector of 4.0 (also normalized)
model.eval()
with torch.no_grad():
    test = torch.full((1, 16), 1.0, dtype=torch.float32) / 100.0
    out = model(test)        # shape (1,16)
    print("Prediction for x=1 (first 5 dims):", out[0, :5].tolist())


Prediction for x=1 (first 5 dims): [0.26759591698646545, 0.09749311208724976, 0.47954195737838745, 0.4150620698928833, 0.5132388472557068]


In [50]:
print("Addition:\n", A + B)
print("\nSubtraction:\n", A - B)
print("\nElementwise Multiplication:\n", A * B)
print("\nMatrix Multiplication:\n", torch.mm(A, B))
print("\nDivision:\n", A / B)
print("\nTranspose:\n", A.T)
print("\nMean of A:", A.float().mean())
print("\nMax of B:", B.max())

Addition:
 tensor([[0.8100, 0.6700, 0.8300, 0.9000, 0.8100, 1.1000, 0.8700, 0.6000, 1.2500,
         1.3000, 0.5400, 1.3500, 1.0300, 1.5100, 1.2000, 1.0400],
        [0.7600, 0.6500, 0.4100, 0.3800, 0.9500, 1.4400, 1.0500, 1.6700, 0.7400,
         0.9300, 0.9900, 0.9400, 0.4800, 1.0400, 0.7700, 1.0600],
        [1.1600, 0.8200, 1.5500, 1.8400, 1.6600, 0.6700, 1.5500, 1.6300, 1.2400,
         1.1500, 0.7600, 1.7300, 1.0100, 0.9800, 0.6200, 0.9900],
        [0.0800, 0.8500, 0.4800, 0.7800, 0.8700, 1.1100, 1.7400, 0.9700, 1.3500,
         0.4000, 0.7900, 0.3700, 0.4500, 1.3700, 1.8600, 0.9800],
        [1.2200, 0.6700, 0.9600, 0.5300, 1.2000, 0.4400, 1.0400, 0.3600, 0.4500,
         1.3700, 0.4600, 0.7600, 1.1900, 0.6600, 0.7900, 1.1300],
        [1.0600, 0.6900, 1.0300, 0.9200, 1.6800, 1.1100, 1.0600, 1.4000, 0.5500,
         1.0300, 1.0400, 1.1300, 0.2700, 0.8900, 0.9400, 1.0400],
        [0.7500, 0.9300, 0.1400, 0.6500, 0.7000, 1.1300, 0.9700, 0.4400, 0.4200,
         1.7900, 0.3800, 1