In [6]:
import tensorflow as tf
import numpy as np

# Create random integer tensors
a = tf.random.uniform(shape=[16, 16], minval=0, maxval=101, dtype=tf.int32)
b = tf.random.uniform(shape=[16, 16], minval=0, maxval=101, dtype=tf.int32)

print("Addition:\n", tf.add(a, b))
print("\nSubtraction:\n", tf.subtract(a, b))
print("\nElement-wise Multiplication:\n", tf.multiply(a, b))
print("\nMatrix Multiplication:\n", tf.matmul(a, b))
print("\nDivision:\n", tf.divide(a, b))
print("\nMean of A:", tf.reduce_mean(a))
print("\nMax of B:", tf.reduce_max(b))
print("\nTranspose of A:\n", tf.transpose(a))

# Broadcasting example (adding identity matrix)
c = tf.eye(num_rows=16, dtype=tf.int32)
print("\nBroadcasted Add:\n", a + c)

# Reshaping and slicing
arr = tf.constant(np.arange(1, 13), shape=(3, 4))
print("\nOriginal:\n", arr)
print("\nSlice [1:3, 1:3]:\n", arr[1:3, 1:3])

# Gradient computation using GradientTape
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2 + 5*x + 2
grad = tape.gradient(y, x)
print("\nGradient of y = x² + 5x + 2 at x=3:", grad.numpy())

Addition:
 tf.Tensor(
[[126  29 140  87 103 142  56 143 110 117  93 142 145 134  95  40]
 [ 89  28 127 139  32 175  48  66 120  53  32  93  94   1 109 121]
 [ 97 114  47  87 128  35 129 160 106  26  97  68  40  70 111 105]
 [ 69  96  88  48  49 171 106  90 115  92  98 133  83  59 139  88]
 [127  19  86 117 121  44 104 131 112  27  98 177  14  89 114  60]
 [149  62 162  57  78 127 107 119  83  38 160 112  42 137  97  73]
 [ 72 100  46 165 139  42  84 134  96 186 137  99 120  54  59  96]
 [119  62  81   9 145  79  39  43  76 110 113  91  95  98  66  91]
 [ 18   5 124  94 122 135 147  31 181  36  95 144  58 111  81 115]
 [ 82  24  14 180 135  59 168  87  81  78  70  96  84  93  75  62]
 [120  43  86  95  68 104 145 108   8 164  70 156  55  78 171  51]
 [122  41 147  80 122 178 144  68 125  85  97  25 126  38 128 112]
 [115  96 115  40  87  64 112 136 111 104 114  24  75  63  86 116]
 [ 83 104 127 106  76  78  63 160  51  88 146  54 169  95 140 154]
 [120 180 102  71 118 119  78 108 103  7

In [7]:
import torch
import numpy as np

A = torch.randint(low=0, high=101, size=(16, 16))
B = torch.randint(low=0, high=101, size=(16, 16))

# Basic operations
print("Addition:\n", A + B)
print("\nSubtraction:\n", A - B)
print("\nElementwise Multiplication:\n", A * B)
print("\nMatrix Multiplication:\n", torch.mm(A, B))
print("\nDivision:\n", A / B)
print("\nTranspose:\n", A.T)
print("\nMean of A:", A.float().mean())
print("\nMax of B:", B.max())

# Reshape and concatenate
C = torch.arange(1, 13).reshape(3, 4)
print("\nOriginal Tensor C:\n", C)
print("\nReshaped (2,6):\n", C.reshape(2,6))
print("\nConcatenation along rows:\n", torch.cat([A, B], dim=0))

# Automatic differentiation
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 5*x + 2
y.backward()
print("\nGradient dy/dx at x=3:", x.grad.item())


Addition:
 tensor([[103,  35,  43, 121, 138,  78, 104, 105, 165, 133,  88, 112, 108,  39,
         134,  73],
        [ 94,  79,  69, 146, 109,  15, 141, 139,  79, 161,  62,  99,  92, 112,
         123, 108],
        [148, 184, 129, 139,  43, 108,  60,  96, 128, 145,  88,  87, 131, 158,
          91,  94],
        [ 28, 141,  85,  44, 135, 162,  97, 116, 162,  96,  69, 129,  70,  93,
         138,  26],
        [ 98,  63, 185, 103, 112,  46,  80,  90, 103,  81, 161,  74,  64, 109,
         177,  43],
        [ 34, 138, 124, 127, 159,  48,  22, 104,  63, 108,  11, 158, 108, 117,
          93,  78],
        [103, 137,  93, 107,  71,  20,  94, 155, 115,  58,  57, 133, 139,  64,
         154, 110],
        [ 77, 137, 114, 123,  43, 182, 116, 117,  39, 158,  61,  97,  79,  55,
          22,  95],
        [ 76,  61, 113,  75,  84,  95, 103, 141,  93,  94, 159,  99,  91, 113,
         103, 181],
        [103, 109,  24, 132, 107,  15,  62,  83,  70, 100, 159, 120,  85, 113,
          62, 136],